---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos/7
    provisioner:
      require_chef_omnibus: 12.8.1
    driver:
      network:
        - ['private_network', {ip: '10.1.1.10'}]
      gui: false

suites:
  - name: default
    data_bags_path: "../../data_bags"
    encrypted_data_bag_secret_key_path: "/home/bob/.secrets/bob_infra_secret"
    run_list:
      - recipe[bob_jenkins::default]
    attributes:
